# General Settings
title = "Bernd - Clean & Minimal Portfolio Hugo Theme"
baseURL = "" #YOUR SITE URL
languageCode = "en-us"
theme = "bernd"
resourceDir = "resources"
paginate = 5
summaryLength = 50
DefaultContentLanguage = "en" # Site language. Available translations in the theme's `/i18n` directory.


# Menu Settings
[menu]
[[menu.main]]
  identifier = "home"
  name = "Home"
  url = ""
  weight = 1
  [[menu.main]]
    identifier = "text-home"
    parent = "home"
    name = "Text"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "parallax-home"
    parent = "home"
    name = "Parallax"
    url = "/parallax-home/"
    weight = 2
  [[menu.main]]
    identifier = "slider-home"
    parent = "home"
    name = "Slider"
    url = "/slider-home/"
    weight = 3
[[menu.main]]
  identifier = "about"
  name = "About"
  url = ""
  weight = 2
  [[menu.main]]
    identifier = "about-me"
    parent = "about"
    name = "About me"
    url = "/about-me/"
    weight = 1
  [[menu.main]]
    identifier = "about-us"
    parent = "about"
    name = "About us"
    url = "/about-us/"
    weight = 2
[[menu.main]]
  identifier = "portfolio"
  name = "Portfolio"
  url = ""
  weight = 3
  [[menu.main]]
    identifier = "portfolio-tiles"
    parent = "portfolio"
    name = "Tiles"
    url = "/portfolio-tiles/"
    weight = 1
  [[menu.main]]
    identifier = "portfolio-masonry"
    parent = "portfolio"
    name = "Masonry"
    url = "/portfolio-masonry/"
    weight = 2
  [[menu.main]]
    identifier = "portfolio-infinity"
    parent = "portfolio"
    name = "Infinity"
    url = "/portfolio-infinity/"
    weight = 3
  [[menu.main]]
    identifier = "portfolio-justified"
    parent = "portfolio"
    name = "Justified"
    url = "/portfolio-justified/"
    weight = 4
  [[menu.main]]
    identifier = "portfolio-single"
    parent = "portfolio"
    name = "Project Single"
    url = ""
    weight = 6
    [[menu.main]]
    identifier = "single-v1"
    parent = "portfolio-single"
    name = "Single v1"
    url = "/portfolio/ideas/"
    weight = 1
    [[menu.main]]
    identifier = "single-v2"
    parent = "portfolio-single"
    name = "Single v2"
    url = "/portfolio/bottle/"
    weight = 2
    [[menu.main]]
    identifier = "single-v3"
    parent = "portfolio-single"
    name = "Single v3"
    url = "/portfolio/bag/"
    weight = 3
    [[menu.main]]
    identifier = "single-v4"
    parent = "portfolio-single"
    name = "Single v4"
    url = "/portfolio/poster/"
    weight = 4
[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = ""
  weight = 4
    [[menu.main]]
    identifier = "classic"
    parent = "blog"
    name = "Classic"
    url = "/blog-classic/"
    weight = 1
    [[menu.main]]
    identifier = "minimal"
    parent = "blog"
    name = "Minimal"
    url = "/blog-minimal/"
    weight = 2
    [[menu.main]]
    identifier = "grid"
    parent = "blog"
    name = "Grid"
    url = "/blog-grid/"
    weight = 3
    [[menu.main]]
    identifier = "full-width"
    parent = "blog"
    name = "Full width"
    url = "/blog-full-width/"
    weight = 4
    [[menu.main]]
    identifier = "post-format"
    parent = "blog"
    name = "Post Format"
    url = "/categories/post-format/"
    weight = 5
[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = ""
  weight = 5
    [[menu.main]]
    identifier = "contact-v1"
    parent = "contact"
    name = "Contact v1"
    url = "/contact-v1/"
    weight = 1
    [[menu.main]]
    identifier = "contact-v2"
    parent = "contact"
    name = "Contact v2"
    url = "/contact-v2/"
    weight = 2

# Main Settings
[params]
defaultLogo = "Bernd."
defaultKeywords = ["clean", "minimal", "blog", "responsive", "google analytics", "bootstrap", "portfolio", "personal", "modern", "parallax", "hugo theme", "creative"]
defaultDescription = "Bernd - Clean & Minimal Portfolio Hugo Theme"
dateFormat = "January 2, 2006"
authorName = "Mountain-Themes"
disqusComments = "" #YOUR DISQUS COMMENTS SHORTNAME
formspreeFormID = "" #YOUR FORMSPREE FORM ID
reCAPTCHAKey = "" #YOUR reCAPTCHA v2 key
googleMapsApiKey = "" #YOUR GOOGLE API KEY

# Sidebar Settings
[params.sidebar]
enable = 0 #SIDEBAR SHOW: [ 1 - yes, 0 - no ] For General page "Blog"
search = 1 #SIDEBAR SEARCH WIDGET: [ 1 - yes, 0 - no ]
latestPosts = 1 #SIDEBAR LATEST POSTS WIDGET: [ 1 - yes, 0 - no ]
categories = 1 #SIDEBAR CATEGORIES TAXONOMY WIDGET: [ 1 - yes, 0 - no ]
tags = 1 #SIDEBAR TAG TAXONOMY WIDGET: [ 1 - yes, 0 - no ]

[params.about]
about = 1 #SIDEBAR ABOUT WIDGET: [ 1 - yes, 0 - no ]
image = "images/author-blog.jpg"
text = "<p>Can't multiply. Set set created thing light blessed third without. Him can't kind called set is second thing from you'll tree. Seed darkness you. Itself night. Life. Hath creature good.</p>"
[[params.about.social]]
icon = "fa-brands fa-instagram"
url = "https://www.instagram.com/"
[[params.about.social]]
icon = "fa-brands fa-facebook"
url = "https://facebook.com/"
[[params.about.social]]
icon = "fa-brands fa-dribbble"
url = "https://dribbble.com/"
[[params.about.social]]
icon = "fa-brands fa-youtube"
url = "https://www.youtube.com/"

[params.subscribe]
subscribe = 1 #SIDEBAR SUBSCRIBE WIDGET: [ 1 - yes, 0 - no ]
mailChimpURL = "https://stevedogs.us9.list-manage.com/subscribe/post?u=df0aa2ea10f32337b29b342d4&id=41ddc569b4"  # Example MailChimp url: http://xxx.xxx.list-manage.com/subscribe/post?u=xxx&id=xxx

# Portfolio Settings (Filter)
[params.portfolio]
[[params.portfolio.filters]]
name = "Branding"
slug = "branding"
[[params.portfolio.filters]]
name = "Design"
slug = "design"
[[params.portfolio.filters]]
name = "Illustration"
slug = "illustration"

# Preloader Settings
[params.preloader]
preloader = 1 #PRELOADER SITE: [ 1 - yes, 0 - no ]

# Footer Settings
[params.footer]
copyright = "Bernd © 2023. Design & Coded by <a href='http://themeforest.net/user/Mountain-Themes' target='_blank'> Mountain-Themes.</a>"

# Social Settings
[[params.social]]
title = "YouTube"
icon = "fa-brands fa-youtube"
url = "https://www.youtube.com/"
[[params.social]]
title = "Twitter"
icon = "fa-brands fa-twitter"
url = "https://www.twitter.com/"
[[params.social]]
title = "Facebook"
icon = "fa-brands fa-facebook"
url = "https://facebook.com/"
[[params.social]]
title = "Dribbble"
icon = "fa-brands fa-dribbble"
url = "https://www.dribbble.com/"
[[params.social]]
title = "Instagram"
icon = "fa-brands fa-instagram"
url = "https://www.instagram.com/"

# Sitemap Settings
[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[outputs]
home = ["HTML", "RSS", "JSON"]