name = "bernd"
license = "GPL"
licenselink = "https://themeforest.net/licenses/terms/regular"
description = "Bernd - Clean & Minimal Portfolio Hugo Theme"
homepage = "https://mountainthemes.dev/"
tags = ["clean", "minimal", "blog", "responsive", "google analytics", "bootstrap", "portfolio", "personal", "modern", "parallax", "contact form", "creative"]
features = ['bootstrap 5', 'responsive design', 'blog', 'responsive', 'minimal', 'one page', 'portfolio', 'hugo-theme', 'parallax', 'creative', 'contact-form']
min_version = "0.91.2"

[author]
  name = "Mountain-Themes"
  homepage = "https://themeforest.net/user/mountain-themes"
